Repository Augugrumi/GestioneImpreseInformaticheNotes, pull requests merged in 2018-05, with the labels that each got.

#37 Pulizia e riordino dei contenuti del documento
  dictionary.it.pws
  res/sections/10-Lez27022018.tex
  res/sections/50-Lez04042018.tex
  res/sections/85-Appendix.tex
  res/sections/86-JobInterview.tex
Labels: enhancement, priority:medium, review

#44 Little changhes chapters 5-9
  res/sections/35-Lez21032018.tex
  res/sections/40-Lez27032018.tex
  res/sections/55-Lez11042018.tex
  res/sections/60-Lez17042018.tex
  res/sections/65-Lez18042018.tex
Labels: bug, enhancement, review

#39 Proof reading
  .gitignore
  config/config.tex
  config/package.tex
  dictionary.it.pws
  res/sections/06-Index.tex
  res/sections/10-Lez27022018.tex
  res/sections/15-Lez28022018.tex
  res/sections/20-Lez06032018.tex
Labels: enhancement, priority:medium, review

#45 Little changes lez 02 05 2018
  dictionary.it.pws
  res/sections/75-Lez02052018.tex
Labels: enhancement, review

#43 Little changes ch4
  res/sections/25-Lez07032018.tex
  res/sections/30-Lez14032018.tex
  res/sections/35-Lez21032018.tex
Labels: bug, enhancement, review

#46 Correzione fino al capitolo 6
  dictionary.it.pws
  res/img/bm_canvas.jpg
  res/img/competitor_analysis.png
  res/img/gamification.png
  res/img/prices_distribution.png
  res/sections/20-Lez06032018.tex
  res/sections/30-Lez14032018.tex
  res/sections/35-Lez21032018.tex
  res/sections/40-Lez27032018.tex
  res/sections/45-Lez28032018.tex
  res/sections/50-Lez04042018.tex
  res/sections/55-Lez11042018.tex
  res/sections/60-Lez17042018.tex
  res/sections/65-Lez18042018.tex
Labels: enhancement, priority:medium, review

#48 Riordinata lista come nel libro
  res/sections/55-Lez11042018.tex
Labels: enhancement, priority:low, review

#47 Correzioni Lez 08 05
  res/img/bm_ex_tel.png
  res/sections/80-Lez08052018.tex
Labels: enhancement, priority:medium, review

#35 Riassuntone del capitolo 5
  dictionary.it.pws
  res/sections/55-Lez11042018.tex
  res/sections/65-Lez18042018.tex
Labels: enhancement, priority:low, review

#50 Fix steps order
  res/sections/25-Lez07032018.tex
Labels: bug, priority:high, review

#51 Fix lez2305
  dictionary.it.pws
  res/img/unboldedcompanytelco.png
  res/sections/81-Lex23052018.tex
Labels: enhancement, priority:medium, review
