Repository Augugrumi/GestioneImpreseInformaticheNotes, pull requests merged in 2018-03, with the labels that each got.

#1 Aggiunte modifiche alla prima lezione (27/02)
  config/config.tex
  res/sections/10-Lez27022018.tex
Labels: review

#3 Piccole correzioni agli appunti della terza lezione (06/03)
  res/sections/20-Lez06032018.tex
Labels: enhancement, review

#8 Fix lezione 0703
  dictionary.it.pws
  res/sections/25-Lez07032018.tex
Labels: enhancement, review

#13 Fix typo
  dictionary.it.pws
  res/sections/10-Lez27022018.tex
Labels: bug, priority:low, review

#11 Small integrations (14/03)
  dictionary.it.pws
  res/img/chartFailureStartup.png
  res/sections/30-Lez14032018.tex
Labels: enhancement, priority:medium, review

#10 Small refinements (07/03)
  res/sections/25-Lez07032018.tex
Labels: enhancement, priority:medium, review

#17 Add releases support
  .travis.yml
Labels: enhancement, priority:medium, review

#16 Lezione2103
  dictionary.it.pws
  res/img/hypecycle.png
  res/img/hypecycle2017.png
  res/sections/35-Lez21032018.tex
Labels: enhancement, priority:low, review

#18 Add new image and resize it
  res/img/chartFailureStartup.png
  res/sections/30-Lez14032018.tex
Labels: enhancement, priority:low, review

#21 Piccole aggiunte lez2103
  .gitignore
  dictionary.it.pws
  res/sections/35-Lez21032018.tex
Labels: review

#22 Aggiunte lezione 2703
  dictionary.it.pws
  res/sections/40-Lez27032018.tex
Labels: enhancement, review

#23 Fix prototype definition
  res/sections/25-Lez07032018.tex
Labels: review
